### ISSUE TITLE
Mistake in (S26)?

### ISSUE THREAD

**Issue by jw3126** [aamini/evidential-deep-learning#10]
First of all thanks a lot for this repo and the papers! I think there is a mistake in (S26) that is also present in the code.
![image](https://user-images.githubusercontent.com/7261506/131534525-86ffbb70-23e0-4c18-99a5-f30022c0f4df.png)

Both Student-t and Normal Inverse Gamma often have a parameter named ν. It seems that these two parameters are confused in the log(π/ν) summand. I think that summand should be log(π/ν_student) = log(π/(2α)) instead.
I think this is also wrong in the code:

https://github.com/aamini/evidential-deep-learning/blob/d1d8e395fb083308d14fa92c5ce766e97b2a066a/evidential_deep_learning/losses/continuous.py#L34

**Comment by HareshKarnan** [comment]
Hey, I went through this math. I think the equation given in the paper is accurate. Can you elaborate on why you think the ν is wrong?

**Comment by jw3126** [comment]
Wow, thanks a lot for looking into this. I really appreciate it! 

Edit: Never mind. I found an error in my own derivation. After correcting it, I get the same result.
